### ISSUE TITLE
如何在柱形图上面显示y坐标的值

### ISSUE THREAD

**Issue by 51bitquant** [ZhipingYang/UUChartView#11]
如何让在柱形图上面的上面标注y坐标的值？

**Comment by 51bitquant** [comment]
如何显示每个y坐标的值呢？

**Comment by ZhipingYang** [comment]
可以看看源码。里面都有的。道理和lineChart显示最大最小值是一样的

**Comment by 51bitquant** [comment]
你怎么不更新这个库了，提供更共一些功能啊？

**Comment by ZhipingYang** [comment]
好的，一直比较忙。

**Comment by 51bitquant** [comment]
我之前改过你的代码。在上面显示具体的y轴的数值，效果还行，iPad效果不是很好。

**Comment by ZhipingYang** [comment]
应该是字号的线条宽度等问题吧

**Comment by 51bitquant** [comment]
是Label的位置。在iphone上时，Label可以一直在柱形图的最上面，而在Ipad上的话，Label不能一在柱形图的最上面。

**Comment by SunnySunning** [comment]
怎么在barchart中显示网格线中的横线

**Comment by ZhipingYang** [comment]
没有去做，道理是一样的
