### ISSUE TITLE
曲线图有办法左右滑动吗？

### ISSUE THREAD

**Issue by pulller** [ZhipingYang/UUChartView#12]
曲线图有办法左右滑动吗？代码里貌似只有柱状图才能左右滑动。

**Comment by ZhipingYang** [comment]
#3

**Comment by ZhipingYang** [comment]
点击查看 #3

**Comment by pulller** [comment]
感谢回复。我用了个比较笨但是简单的方法，临时修改了一下UULineChart.m文件中的setXLabels函数，将最大限制由20改成了31，因为要用到按照月份显示（31天）的功能。然后x坐标的label每隔一个显示，坐标文字就避免了重叠。

**Comment by maxfong** [comment]
@pulller 模仿UUBarChart，在UULineChart中添加myScrollView，是个不错的办法。
