### ISSUE TITLE
如何重新绘制

### ISSUE THREAD

**Issue by wangdachui2060** [ZhipingYang/UUChartView#15]
如何重新绘制？strokeChart 不会清除之前绘制的，没有相关方法调用重绘？ 怎么解决？

**Comment by ZhipingYang** [comment]
sorry, 很久没有去维护升级了。
我的demo里面是直接使用 [chartView removeFromSuperview] 来处理的。
你可以修改原方法：
    [chartView showInView:self.contentView];
为：
    [chartView showInView:self.contentView withAnimation:YES];
来处理。这样也可以。就是添加一个参数

**Comment by jiang443** [comment]
chatView.removeFromSuperview()
        chatView = UUChart(frame: rect, dataSource: self, style: .Line)
        chatView.showInView(self.dataView)

**Comment by ZhipingYang** [comment]
reloadData
