### ISSUE TITLE
不知道为什么x轴文字就是显示不了

### ISSUE THREAD

**Issue by fifyrio** [ZhipingYang/UUChartView#16]
- (NSArray *)UUChart_xLableArray:(UUChart *)chart{
  return [self getXTitles:7];
  }
- (NSArray *)getXTitles:(int)num
  {
  NSMutableArray *xTitles = [NSMutableArray array];
  for (int i=0; i<num; i++) {
      NSString \* str = [NSString stringWithFormat:@"R-%d",i];
      [xTitles addObject:str];
  }
  return [xTitles copy];
  }
  x轴是这样写的，但是最终显示是这样

求楼主指导，不甚感激

**Comment by fifyrio** [comment]
OK了，原来是在viewdidLoad加载了chartView的原因，viewdidLoad里的frame不准，导致UUBarChart里的myScrollViewd frame不准，解决方法就是在viewDidAppear里创建chartView

**Comment by ZhipingYang** [comment]
嗯， 这个库目前还有很多缺陷。找到临时解决方案就好
