### ISSUE TITLE
可以定义显示lineChart的显示范围吗？

### ISSUE THREAD

**Issue by maimemo** [ZhipingYang/UUChartView#2]
就是，比如我的数据有很多月份，从2001年1月到2014年12月，但是我想它的视觉范围只显示6个月的内容，滑动屏幕显示其他月份的，是否可以实现？

**Comment by ZhipingYang** [comment]
目前只有Bar可以左右滑动，要实现需要你去去设定scrollView的ContentOffSet。如果只显示6个月的内容，那么显示容量要手动修改成6.
