### ISSUE TITLE
能不能每个转折点都显示具体数值？

### ISSUE THREAD

**Issue by tanbinzone** [ZhipingYang/UUChartView#24]

**Comment by ZhipingYang** [comment]
可以是可以，我限制最大最小值显示。去除限制就可以

**Comment by levinli303** [comment]
怎么修改呢？

**Comment by isnine** [comment]
请问怎么修改~能稍微提示下删除那些限制么

**Comment by ZhipingYang** [comment]
https://github.com/ZhipingYang/UUChartView/blob/master/UUChart/UULineChart.m#L205

isShowMaxAndMinPoint 换成YES
