### ISSUE TITLE
横坐标数据超过20个以后不显示了

### ISSUE THREAD

**Issue by TomasRay** [ZhipingYang/UUChartView#27]
请问这个怎么解决呢？比如我要显示30个数据走势，现在只能显示到20个。

**Comment by TomasRay** [comment]
好吧，看了下，解决了，谢谢了。

**Comment by ganjmeng** [comment]
怎么解决的，跪求啊😳

**Comment by shen5214444887** [comment]
作者的代码书写还是很规范的，你可以全局搜索20，然后修改横坐标数值。
其实还是希望作者把这样一些属性都开放出来，方便修改，不需要一个一个的去找，然后去修改

**Comment by ganjmeng** [comment]
这样啊，多谢了
