### ISSUE TITLE
Could you please provide the code for fill Color between two Line Charts 

### ISSUE THREAD

**Issue by Rajitha-Gangam** [ZhipingYang/UUChartView#29]
Hi,
We have implemented Line, Bar Charts in our application and Customer also liked this graphs UI and animation.
But We have immediate requirement that, we need to fill with color between two Line charts for one Graph.
I tried a lot, but I could not get it resolve, Could you please help me to get out of this issue.
Thanks

**Comment by ZhipingYang** [comment]
[image: Inline image 1]
did you mean to draw the graph area like this?
