### ISSUE TITLE
可以让折线图左右滑动吗

### ISSUE THREAD

**Issue by gdfyj90** [ZhipingYang/UUChartView#3]
我发现你的UUBarChart有scrollview，为什么UULineChart不添加呢。

**Comment by ZhipingYang** [comment]
是这样的，我认为lineChart点阵可以放下很多数据差不多至少20个，但是相对于barChart有对比两组数据时6个差不多是极限了。所以就没有加上去

**Comment by gdfyj90** [comment]
那如果添加scrollview的话是直接初始化scrollview然后addsubview UULineChart对象就可以了吗？

**Comment by ZhipingYang** [comment]
要加载到scrollview的layer上，网格也要相应放上去
