### ISSUE TITLE
Line chart adding two legends

### ISSUE THREAD

**Issue by tutysathish** [ZhipingYang/UUChartView#37]
Hi,
I am trying to add two legends into one line chart
say for example,
**A, B**
A = {10, 11, 12} for {10/03/2017, 11/03/2017, 12/03/2017}
B = {15,17} for {10/03/2017, 12/03/2017}

The above data was not populated correctly in my chart.
So, can you help me to solve this.

**Comment by ZhipingYang** [comment]
So far, this repo cannot solve this issue, but if you like, you can change your data in this way.

A = {10, 11, 12} for {10/03/2017, 11/03/2017, 12/03/2017}
B = {15,**(15+17)/2**,17} for {10/03/2017, **(10+12)/2**/03/2017, 12/03/2017}

**Comment by tutysathish** [comment]
Thank you, I will try this one.
