### ISSUE TITLE
Multiple colours on single bar. 

### ISSUE THREAD

**Issue by kalyan711987kalyan** [ZhipingYang/UUChartView#39]
How to add multiple colours on same bar. Based on bar percentage , i need to show the colours.
60% of bar with one colour, other 40% of bar with another colour

**Comment by ZhipingYang** [comment]
[chartLine](https://github.com/ZhipingYang/UUChartView/blob/master/UUChart/UUBar.h#L15) is a property of [UUBar](https://github.com/ZhipingYang/UUChartView/blob/master/UUChart/UUBar.h) whitch is a CALayer class. so If you want to show different colors on this, just add and config two sublayers.

have fun!

**Comment by kalyan711987kalyan** [comment]
Thanks, will try.
