### ISSUE TITLE
背景颜色可更改吗

### ISSUE THREAD

**Issue by joseph-517** [ZhipingYang/UUChartView#4]
UUBar.m中的
- (void)drawRect:(CGRect)rect{
  //Draw BG
  CGContextRef context = UIGraphicsGetCurrentContext();
  CGContextSetFillColorWithColor(context, [UIColor whiteColor].CGColor);
  CGContextFillRect(context, rect);
  }

換成CGContextSetFillColorWithColor(context, [UIColor clearColor].CGColor);
背景的barchart变成黑色
如何更改成透明的？

**Comment by joseph-517** [comment]
已經解決
UUBarChart.m中
-(void)strokeChart{
     UUBar \* bar;
     bar.backgroundColor = [UIColor clearColor];
}

**Comment by kvnbautista** [comment]
@starkite https://github.com/seanchain/iOSChart

**Comment by ZhipingYang** [comment]
:+1:
