### ISSUE TITLE
如何更新数据

### ISSUE THREAD

**Issue by lifengios** [ZhipingYang/UUChartView#40]

**Comment by ZhipingYang** [comment]
我最近开始维护升级一下，目前你只能先调用 UUChart 的 `- (void)strokeChart;`方法重载

**Comment by wongshouxin** [comment]
大佬怎么刷新柱状图的数据。没找到方法，如果每次在获取网络数据成功后，添加 chartView，会有重叠。有更好的方法吗？？？

**Comment by wongshouxin** [comment]
@ZhipingYang

**Comment by ZhipingYang** [comment]
sorry啊，之前重构一半半，还没有完成。调用reloadData，但不知道有没有bug😂

https://github.com/ZhipingYang/UUChartView/blob/develop/UUChart/UUChart.h#L54

**Comment by wongshouxin** [comment]
这个版本没有 reload方法。还是很期待啊  大佬，加油重构，这个UUChart就完美了。

**Comment by ZhipingYang** [comment]
done
