### ISSUE TITLE
yLabel出现Label重叠

### ISSUE THREAD

**Issue by lifengios** [ZhipingYang/UUChartView#42]
背景色是clear ，yLabel就有1 2 3 4 5 和我自己获取数据后的那个yLabel数组，是不是初始化的时候如果数组没值，就默认给的 1 2 3 4 5

**Comment by lifengios** [comment]
是不是这种有图表的，先获取网络数据，再创建chart 比较好

**Comment by ZhipingYang** [comment]
你可以先获取数据再绘制图表啊。我最近是需要加一个reloadData的功能。label重叠可以详细描述？有图最好了

**Comment by wqforever** [comment]
我也遇到了，使用strokeChart这个函数有重叠

**Comment by wqforever** [comment]
现在解决方案是我在setYLabels里把以前的Ylabel移除， 
 for (UIView *view in self.subviews) {
        if ([view isKindOfClass:[UUChartLabel class]]) {
            [view removeFromSuperview];
        }
    }
