### ISSUE TITLE
2条曲线，前面都会重叠

### ISSUE THREAD

**Issue by XiaoXiuXiuYe** [ZhipingYang/UUChartView#53]
我是在一个view里面添加了折线图，设置了delegate和datasource的代理为view，在里面实现了代理方法，根据服务器返回的值，设置数据后，2条曲线，前面都会重叠，点击显示时，值又是对的，比如，有一条曲线的值是	9341.00,9300.00，9200.00，838500.00，838500.00，838500.00，838500.00 ，第二条曲线的值，0，0，0，0 ，0，0，0，可是2条曲线，前面都重叠了，点击第一个点后，显示出来第一条曲线的值又是9341.00，我不知道是不是我哪里弄错了，还请帮忙解答一下。

**Comment by XiaoXiuXiuYe** [comment]
我自己弄错了

**Comment by ZhipingYang** [comment]
哈哈😄
