### ISSUE TITLE
Line Graphic does not show all my values

### ISSUE THREAD

**Issue by erdemgc** [ZhipingYang/UUChartView#6]
Hi ,

I have 31 values in my graphic but only 21 of them is shown. Although i change the size of my line graphic view size it is still the same, it just strecthes, but not show all values.

What might be wrong?

**Comment by erdemgc** [comment]
Now I have tested the sample project, it is same on the sample project, values count greater than 21 is not shown on the screen.

**Comment by ZhipingYang** [comment]
in UULineChart.h 

-(void)setXLabels:(NSArray *)xLabels
{
    _xLabels = xLabels;
    CGFloat num = 0;
    if (xLabels.count>=20) {
        num=20.0;
    }else if (xLabels.count<=1){
        num=1.0;
    }else{
        num = xLabels.count;
    }
    _xLabelWidth = (self.frame.size.width - UUYLabelwidth)/num;

**Comment by ZhipingYang** [comment]
you need change max number by yourself
