### ISSUE TITLE
如果xLabel过长，一行显示不下，怎样才是最好的处理方式呢？

### ISSUE THREAD

**Issue by CaliosD** [ZhipingYang/UUChartView#7]
我试图将UUChartLabel中的numberOfLines设置成0，或是在给label.text赋值之后增加[label sizeToFit]; 但是都不管用，文字都只显示一半，要么是前一半，要么是上一半，请问有什么好的解决办法吗？

**Comment by shen5214444887** [comment]
你将UUChartView放在一个scrollView上面，将宽设置为屏幕的2倍以上，这样就可以显示了

**Comment by ZhipingYang** [comment]
done, 定制 rowWidth
